theme: jekyll-theme-minimal
title: "Jikken Records"
description: "Define The Future Shape of Sounds"
logo: "https://raw.githubusercontent.com/adrien-mogenet/jikken/gh-pages/logo.jpg"
google_analytics: "UA-162787589-1"
